"""Write data/split_v2.js: per-tile band, block and per-fold roles of the proposed v2 split
(data/splits/model_design_exp_split_v2.csv), patched over CLARIDI.tiles by splits_v2.html."""
import csv, json, os
R = "/local/emir/ClariDi"
OUT = os.path.dirname(os.path.abspath(__file__))
rows = {r["tile_id"]: r for r in csv.DictReader(open(f"{R}/data/splits/model_design_exp_split_v2.csv"))}
data = {t: dict(b=int(r["band"]), u=r["block"].split("_")[-1], ou=r["unit"].split("_")[-1],
                r=[r[f"role_f{k}"] for k in range(5)]) for t, r in rows.items()}
with open(f"{OUT}/data/split_v2.js", "w") as f:
    f.write("/* generated by build_split_v2.py */\nwindow.CLARIDI_SPLIT = ")
    json.dump(data, f, separators=(",", ":")); f.write(";\n")
print(len(data), "tiles")
