"""Replace the metric tables in index.html with those of analysis/v2/metrics_all_draws.md.

The block between <!-- METRICS:BEGIN --> and <!-- METRICS:END --> is regenerated; everything else is hand-written.
  python website_ClariDi/tools/insert_metrics.py
"""
import html, os, re

R = "/local/emir/ClariDi"
SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MD = f"{R}/analysis/v2/metrics_all_draws.md"


def cells(line):
    parts = re.split(r"(?<!\\)\|", line.strip().strip("|"))
    return [html.escape(p.strip().replace(r"\|", "|")).replace("±", "&plusmn;") for p in parts]


def sections(md):
    """{heading: [rows]} for every '## heading' followed by a markdown table"""
    out, cur = {}, None
    for line in md.splitlines():
        if line.startswith("## "):
            cur = line[3:].strip(); out[cur] = []
        elif cur and line.startswith("|") and not re.match(r"^\|(-+\|)+$", line.strip()):
            out[cur].append(cells(line))
    return out


def table(rows):
    head, body = rows[0], rows[1:]
    return ("<table><tr>" + "".join(f"<th>{c}</th>" for c in head) + "</tr>"
            + "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in body) + "</table>")


def find(sec, prefix):
    k = [h for h in sec if h.startswith(prefix)]
    assert len(k) == 1, (prefix, list(sec))
    n = re.search(r"\(n = (\d+) tiles, (\d+) specimens\)", k[0])
    return sec[k[0]], (n.groups() if n else None)


def main():
    sec = sections(open(MD).read())
    rows, (nt, ns) = find(sec, "All tiles, specimen-macro")
    rows_m, _ = find(sec, "All tiles, tile-micro")
    rows_d, (nd, _) = find(sec, "Without D part 0")
    rows_b, (_, nb) = find(sec, "Brain")
    rows_h, (_, nh) = find(sec, "Heart")
    rows_s, _ = find(sec, "Per specimen")
    block = "\n".join([
        "<!-- METRICS:BEGIN (generated by tools/insert_metrics.py from analysis/v2/metrics_all_draws.md) -->",
        f"  <h3>All {nt} tiles, {ns} specimens</h3>", "  " + table(rows),
        f"  <h3>Without D part 0 ({nd} tiles; sensitivity)</h3>", "  " + table(rows_d),
        '  <details><summary class="small">Tile-micro mean, brain, heart and per-specimen LPIPS</summary>',
        f"  <h3>All {nt} tiles, tile-micro mean (every tile weighted equally)</h3>" + table(rows_m),
        f"  <h3>Brain ({nb} specimens)</h3>" + table(rows_b),
        f"  <h3>Heart ({nh} specimens)</h3>" + table(rows_h),
        "  <h3>Per specimen, LPIPS (tile mean; mean &plusmn; SD across draws)</h3>" + table(rows_s),
        "  </details>",
        "<!-- METRICS:END -->"])
    p = f"{SITE}/index.html"; s = open(p).read()
    a, b = s.index("<!-- METRICS:BEGIN"), s.index("<!-- METRICS:END -->") + len("<!-- METRICS:END -->")
    open(p, "w").write(s[:a] + block + s[b:])
    print("index.html: metric tables replaced from", MD)


if __name__ == "__main__":
    main()
